name: docker-build
on:
  push:
  pull_request:
  schedule:
    - cron: '22 4 20 * *'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile .
